blank_issues_enabled: false
contact_links:
  - name: Question & Discussions
    url: https://github.com/olamide203/hyoka/discussions
    about: Use GitHub discussions for message-board style questions and discussions 